set -g default-terminal "xterm-256color"
set -ga terminal-overrides ",xterm-256color:Tc"
set -g default-shell /opt/homebrew/bin/fish

# Prefix: C-t
unbind C-b
set-option -g prefix C-t
set-option -g repeat-time 0
set-option -g focus-events on

# Vi mode
set-window-option -g mode-keys vi

# Reload config
bind r source-file ~/.config/tmux/tmux.conf \; display "Reloaded!"

# Open current directory in Finder
bind o run-shell "open '#{pane_current_path}'"

# Kill all panes except current
bind -r e kill-pane -a

# New window/pane in current directory
bind c new-window -c "#{pane_current_path}"
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# Moving windows
bind-key -n C-S-Left swap-window -t -1 \; previous-window
bind-key -n C-S-Right swap-window -t +1 \; next-window

# Basic settings
set-option -g status-justify "left"
set-option -g history-limit 64096
set -sg escape-time 10
set -g mouse on

# Title bar adapts to host
set -g set-titles on
set -g set-titles-string "#T"

# macOS clipboard
set-option -g default-command "which reattach-to-user-namespace > /dev/null && reattach-to-user-namespace -l $SHELL || $SHELL"

# Undercurl support
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'

# Import configs
source ~/.config/tmux/theme.conf
source ~/.config/tmux/statusline.conf
source ~/.config/tmux/utility.conf

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-pain-control'
run '~/.config/tmux/plugins/tpm/tpm'
